import { Activity } from '@/types';

// Comprehensive list of activities
export const ACTIVITIES: Activity[] = [
  // Outdoor Activities
  {
    id: 'hiking',
    name: 'Hiking',
    description: 'Explore nature trails and enjoy scenic views',
    category: 'nature',
    intensity: 'high',
    duration: '2-4 hours',
    suitableWeather: ['clear', 'clouds'],
    icon: '🥾',
    tags: ['nature', 'exercise', 'scenic'],
    indoor: false,
    familyFriendly: true,
    priceRange: 'free',
  },
  {
    id: 'picnic',
    name: 'Park Picnic',
    description: 'Relax with food and drinks in a beautiful park',
    category: 'relaxation',
    intensity: 'low',
    duration: '1-3 hours',
    suitableWeather: ['clear', 'clouds'],
    icon: '🧺',
    tags: ['relaxing', 'food', 'social'],
    indoor: false,
    familyFriendly: true,
    priceRange: '$',
  },
  {
    id: 'cycling',
    name: 'Cycling',
    description: 'Bike around the city or nature trails',
    category: 'sports',
    intensity: 'medium',
    duration: '1-3 hours',
    suitableWeather: ['clear', 'clouds'],
    icon: '🚴',
    tags: ['exercise', 'transportation', 'adventure'],
    indoor: false,
    familyFriendly: true,
    priceRange: 'free',
  },
  {
    id: 'beach',
    name: 'Beach Day',
    description: 'Swim, sunbathe, and enjoy the sand and waves',
    category: 'outdoor',
    intensity: 'low',
    duration: '3-6 hours',
    suitableWeather: ['clear'],
    icon: '🏖️',
    tags: ['swimming', 'relaxing', 'summer'],
    indoor: false,
    familyFriendly: true,
    priceRange: 'free',
  },
  {
    id: 'photography',
    name: 'Photography Walk',
    description: 'Capture beautiful moments around your city',
    category: 'outdoor',
    intensity: 'low',
    duration: '1-3 hours',
    suitableWeather: ['clear', 'clouds', 'mist', 'fog'],
    icon: '📷',
    tags: ['creative', 'walking', 'art'],
    indoor: false,
    familyFriendly: true,
    priceRange: 'free',
  },
  {
    id: 'running',
    name: 'Jogging',
    description: 'Get your cardio in with a refreshing run',
    category: 'fitness',
    intensity: 'high',
    duration: '30-60 mins',
    suitableWeather: ['clear', 'clouds'],
    icon: '🏃',
    tags: ['exercise', 'cardio', 'health'],
    indoor: false,
    familyFriendly: true,
    priceRange: 'free',
  },
  {
    id: 'gardening',
    name: 'Gardening',
    description: 'Tend to plants and enjoy nature at home',
    category: 'relaxation',
    intensity: 'low',
    duration: '1-2 hours',
    suitableWeather: ['clear', 'clouds', 'drizzle'],
    icon: '🌱',
    tags: ['nature', 'relaxing', 'home'],
    indoor: false,
    familyFriendly: true,
    priceRange: 'free',
  },
  {
    id: 'outdoor-yoga',
    name: 'Outdoor Yoga',
    description: 'Practice yoga in a park or garden',
    category: 'fitness',
    intensity: 'medium',
    duration: '1 hour',
    suitableWeather: ['clear', 'clouds'],
    icon: '🧘',
    tags: ['wellness', 'relaxing', 'exercise'],
    indoor: false,
    familyFriendly: true,
    priceRange: 'free',
  },
  {
    id: 'farmers-market',
    name: 'Farmers Market',
    description: 'Browse local produce and artisan goods',
    category: 'shopping',
    intensity: 'low',
    duration: '1-2 hours',
    suitableWeather: ['clear', 'clouds'],
    icon: '🍎',
    tags: ['food', 'local', 'shopping'],
    indoor: false,
    familyFriendly: true,
    priceRange: '$',
  },
  {
    id: 'kayaking',
    name: 'Kayaking',
    description: 'Paddle through calm waters and enjoy nature',
    category: 'sports',
    intensity: 'medium',
    duration: '2-3 hours',
    suitableWeather: ['clear'],
    icon: '🛶',
    tags: ['water', 'adventure', 'exercise'],
    indoor: false,
    familyFriendly: true,
    priceRange: '$$',
  },

  // Indoor Activities
  {
    id: 'museum',
    name: 'Museum Visit',
    description: 'Explore art, history, or science exhibitions',
    category: 'cultural',
    intensity: 'low',
    duration: '2-4 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog', 'haze', 'dust'],
    icon: '🏛️',
    tags: ['culture', 'education', 'art'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'movie',
    name: 'Movie Theater',
    description: 'Watch the latest films on the big screen',
    category: 'entertainment',
    intensity: 'low',
    duration: '2-3 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🎬',
    tags: ['entertainment', 'relaxing', 'social'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'cafe',
    name: 'Cozy Café Visit',
    description: 'Enjoy coffee and pastries in a warm atmosphere',
    category: 'food',
    intensity: 'low',
    duration: '1-2 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '☕',
    tags: ['food', 'relaxing', 'social'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$',
  },
  {
    id: 'spa',
    name: 'Spa Day',
    description: 'Relax with massages, saunas, and treatments',
    category: 'relaxation',
    intensity: 'low',
    duration: '2-4 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '💆',
    tags: ['wellness', 'relaxing', 'self-care'],
    indoor: true,
    familyFriendly: false,
    priceRange: '$$$',
  },
  {
    id: 'bowling',
    name: 'Bowling',
    description: 'Fun game for friends and family',
    category: 'entertainment',
    intensity: 'low',
    duration: '1-2 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🎳',
    tags: ['games', 'social', 'fun'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'escape-room',
    name: 'Escape Room',
    description: 'Solve puzzles and escape before time runs out',
    category: 'entertainment',
    intensity: 'medium',
    duration: '1 hour',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🔐',
    tags: ['puzzles', 'teamwork', 'adventure'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'cooking-class',
    name: 'Cooking Class',
    description: 'Learn to prepare delicious dishes',
    category: 'food',
    intensity: 'medium',
    duration: '2-3 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '👨‍🍳',
    tags: ['food', 'learning', 'social'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'gym',
    name: 'Gym Workout',
    description: 'Get fit with weights and cardio machines',
    category: 'fitness',
    intensity: 'high',
    duration: '1-2 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '💪',
    tags: ['exercise', 'health', 'fitness'],
    indoor: true,
    familyFriendly: false,
    priceRange: '$$',
  },
  {
    id: 'shopping-mall',
    name: 'Shopping Mall',
    description: 'Browse stores and enjoy retail therapy',
    category: 'shopping',
    intensity: 'low',
    duration: '2-4 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🛍️',
    tags: ['shopping', 'social', 'entertainment'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'library',
    name: 'Library Visit',
    description: 'Read books and enjoy a quiet atmosphere',
    category: 'cultural',
    intensity: 'low',
    duration: '1-3 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '📚',
    tags: ['reading', 'quiet', 'free'],
    indoor: true,
    familyFriendly: true,
    priceRange: 'free',
  },
  {
    id: 'board-games',
    name: 'Board Game Café',
    description: 'Play classic and modern board games',
    category: 'entertainment',
    intensity: 'low',
    duration: '2-3 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🎲',
    tags: ['games', 'social', 'fun'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$',
  },
  {
    id: 'aquarium',
    name: 'Aquarium',
    description: 'Discover marine life and underwater worlds',
    category: 'cultural',
    intensity: 'low',
    duration: '2-3 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🐠',
    tags: ['nature', 'education', 'family'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'indoor-climbing',
    name: 'Indoor Climbing',
    description: 'Challenge yourself on climbing walls',
    category: 'fitness',
    intensity: 'high',
    duration: '1-2 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🧗',
    tags: ['exercise', 'adventure', 'challenge'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'theater',
    name: 'Theater Show',
    description: 'Watch live performances and plays',
    category: 'cultural',
    intensity: 'low',
    duration: '2-3 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🎭',
    tags: ['culture', 'entertainment', 'art'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$$',
  },
  {
    id: 'indoor-pool',
    name: 'Indoor Swimming',
    description: 'Swim laps or relax in the pool',
    category: 'fitness',
    intensity: 'medium',
    duration: '1-2 hours',
    suitableWeather: ['rain', 'thunderstorm', 'snow', 'drizzle', 'mist', 'fog'],
    icon: '🏊',
    tags: ['swimming', 'exercise', 'relaxing'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },

  // Winter/Snow Activities
  {
    id: 'skiing',
    name: 'Skiing',
    description: 'Hit the slopes for winter fun',
    category: 'sports',
    intensity: 'high',
    duration: '4-6 hours',
    suitableWeather: ['snow'],
    icon: '⛷️',
    tags: ['winter', 'adventure', 'exercise'],
    indoor: false,
    familyFriendly: true,
    priceRange: '$$$',
  },
  {
    id: 'snowboarding',
    name: 'Snowboarding',
    description: 'Carve through fresh powder',
    category: 'sports',
    intensity: 'high',
    duration: '4-6 hours',
    suitableWeather: ['snow'],
    icon: '🏂',
    tags: ['winter', 'adventure', 'extreme'],
    indoor: false,
    familyFriendly: false,
    priceRange: '$$$',
  },
  {
    id: 'ice-skating',
    name: 'Ice Skating',
    description: 'Glide on ice at an indoor or outdoor rink',
    category: 'sports',
    intensity: 'medium',
    duration: '1-2 hours',
    suitableWeather: ['snow', 'clear', 'clouds'],
    icon: '⛸️',
    tags: ['winter', 'fun', 'exercise'],
    indoor: true,
    familyFriendly: true,
    priceRange: '$$',
  },
  {
    id: 'hot-springs',
    name: 'Hot Springs',
    description: 'Warm up in natural hot springs',
    category: 'relaxation',
    intensity: 'low',
    duration: '2-4 hours',
    suitableWeather: ['snow', 'clear', 'clouds'],
    icon: '♨️',
    tags: ['relaxing', 'nature', 'wellness'],
    indoor: false,
    familyFriendly: true,
    priceRange: '$$',
  },
];

export const ACTIVITY_CATEGORIES = [
  { id: 'all', label: 'All', icon: '✨' },
  { id: 'outdoor', label: 'Outdoor', icon: '🌳' },
  { id: 'indoor', label: 'Indoor', icon: '🏠' },
  { id: 'cultural', label: 'Cultural', icon: '🏛️' },
  { id: 'sports', label: 'Sports', icon: '⚽' },
  { id: 'relaxation', label: 'Relaxation', icon: '🧘' },
  { id: 'food', label: 'Food & Drink', icon: '🍽️' },
  { id: 'entertainment', label: 'Entertainment', icon: '🎮' },
  { id: 'nature', label: 'Nature', icon: '🌲' },
  { id: 'fitness', label: 'Fitness', icon: '💪' },
  { id: 'shopping', label: 'Shopping', icon: '🛍️' },
];

export const TIME_OF_DAY = {
  morning: { start: 6, end: 12, label: 'Morning' },
  afternoon: { start: 12, end: 18, label: 'Afternoon' },
  evening: { start: 18, end: 24, label: 'Evening' },
};
